#!/usr/bin/env ruby
=begin
  Script to take tests that are unclassified and indicate that they have failed.
  This also moves the results to the failed directory.
=end

require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

testList = []
ARGV.each do |t|
  `mv test/unclassified/#{t}.test test/failed`
  `mv results/unclassified/#{t}.test results/failed/#{t}.test`
  testList << t
end

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"
status[:tests] = testList

h = History.new
h.log(status)