#!/usr/bin/env ruby

require 'fileutils'
require_relative 'lib/history'
require_relative 'lib/report'

`rm -rf data`
`rm -rf history`
`rm -rf temp`
`rm -rf test`
`rm -rf results`

`mkdir data`
`mkdir history`
`mkdir temp`

`mkdir -p test/new`
`mkdir -p test/passed`
`mkdir -p test/failed`
`mkdir -p test/unclassified`
`mkdir -p test/inactive`

`mkdir -p results/passed`
`mkdir -p results/failed`
`mkdir -p results/unclassified`

# create the tag file
if !File.exist?("data/tag") then
	tag_file = File.new("data/tag", 'w')
	tag_file.close
end

History.start_new_history

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"

h = History.new
h.log(status)