#!/usr/bin/env ruby
#
# Report on the last execution of the test harness 
# (e.g., how many tests passed, how many failed, how many are unclassified, etc.).
#
# Usage: report
#
# Author: jbao2@wpi.edu
# Version: 14-Sep-2014

require_relative 'lib/test_directory.rb'

dirs = ['unclassified', 'passed', 'failed']
Dir.chdir("results")

dirs.each do |dir|
	Dir.chdir(dir)
	new_dir = TestDirectory.new
	count = new_dir.testfile_number
	case dir
		when 'unclassified'
			puts "Unclassified file number: #{count} \n"
		when 'passed'
			puts "Passed file number: #{count} \n"
		when 'failed'
			puts "Failed file number: #{count} \n"
	end
	Dir.chdir("../")
end
Dir.chdir("../")