#!/usr/bin/env ruby
#
# Reset the system so that all tests are new and that there are no results.
#
# Usage: restart-harness [-h -i]
#
# If the "h" parameter is specified, then all history is wiped out;
# otherwise, the history is simply restarted.
#
# @author gpollice, jbao
# @version 15-Sept-2014

require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

`rm results/failed/* results/passed/* results/unclassified/*`
`mv test/failed/* test/new`
`mv test/passed/* test/new`
`mv test/unclassified/* test/new`

`mv test/inactive/* test/new` if ARGV.find '-i'

`rm history/*` if ARGV.find '-h'
`rm temp/*`

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"

h = History.new
h.log(status)