#!/usr/bin/env ruby

# Run one or more specific tests.
# Usage: run test_hello_assembler test_hello_executes
# Author: jbao2@wpi.edu
# Version: 14-Sep-2014

require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

# tag_file = File.open("data/tag", "r")
# tests = []

# ARGV.each do |t|
# 	case t:
# 	when "-t": # run tags
# 		lines = tag_file.readlines
# 		status = {}
# 		status << eval(lines[0]) if lines.length > 0
		
# end



dirs = ['test/unclassified', 'test/new', 'test/passed', 'test/failed', 'test/inactive']
testList = []
ARGV.each do |t|
	# Remove the specific test result
	`rm results/failed/#{t}.test results/passed/#{t}.test results/unclassified/#{t}.test`

	# look for the matched test name
	dirs.each do |dir|
	    Dir.chdir(dir)
	    new_dir = TestDirectory.new
	    new_dir.files.each do |file|
	      
	      if File.basename(file, ".test") == t
	        `#{file} >& ../../results/unclassified/#{file}`
	        new_dir.move(file, '.', '../unclassified') if dir != "test/unclassified"
	        testList << File.basename(file, ".test")
	      end
	    end
	    Dir.chdir("../..")
    end
end

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"
status[:tests] = testList

h = History.new
h.log(status)