#!/usr/bin/env ruby
#
# Run all of the tests in the new directory. When a test is executed it will be
# moved to the unclassified directory and its results will be in the unclassified
# results directory.
#
# Usage: run-new
#
# Author: gpollice@cs.wpi.edu
# Version: 22-Jan-2012
require_relative 'lib/test_directory.rb'

Dir.chdir("test/new")
new_dir = TestDirectory.new
new_dir.files.each do |file|
  if File.extname(file) == ".test"
    base_name = File.basename(file) 
    #
    # History logging should go here.
    #
  
    #
    # run the test and move it to unclassified status
    #
    `#{file} >& ../../results/unclassified/#{base_name}`
    new_dir.move(file, '.', '../unclassified')
  end
end
Dir.chdir("../..")