#!/usr/bin/env ruby
#
# Run all of the tests in the directories including new, passed, failed, unclassified, inactive. 
# When a test is executed it will be moved to the unclassified directory 
# and its results will be in the unclassified
# results directory.
#
# Usage: run-all
#
# Author: jbao2@wpi.edu
# Version: 14-Sep-2014

require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

# remove all the results
`rm results/failed/* results/passed/* results/unclassified/*`

testList = []

dirs = ['test/unclassified', 'test/new', 'test/passed', 'test/failed', 'test/inactive']
dirs.each do |dir|
    Dir.chdir(dir)
    new_dir = TestDirectory.new
    new_dir.files.each do |file|
      if File.extname(file) == ".test"
        `#{file} >& ../../results/unclassified/#{file}`
        new_dir.move(file, '.', '../unclassified') if dir != "test/unclassified"
        testList << File.basename(file, '.test')
      end
    end
    Dir.chdir("../..")
end

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"
status[:tests] = testList

h = History.new
h.log(status)