#!/usr/bin/env ruby
#
# Run all of the tests in the new directory. When a test is executed it will be
# moved to the unclassified directory and its results will be in the unclassified
# results directory.
#
# Usage: run-new
#
# Author: jbao2@wpi.edu
# Version: 11-Sept-2014

require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

Dir.chdir("test/new")
testList = []
new_dir = TestDirectory.new
new_dir.files.each do |file|
  if File.extname(file) == ".test"
    #
    # run the test and move it to unclassified status
    #
    `#{file} >& ../../results/unclassified/#{file}`
    new_dir.move(file, '.', '../unclassified')
    testList << File.basename(file, ".test")
  end
end
Dir.chdir("../..")

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = "#{Time.now}"
status[:tests] = testList

h = History.new
h.log(status)