#!/usr/bin/env ruby
#
# moved unclassified tests to the passed directory
#
# Usage: fail-all
#
# Author: jbao2@wpi.edu
# Version: 14-Sep-2014
require_relative 'lib/test_directory.rb'
require_relative 'lib/history'
require_relative 'lib/report.rb'

testList = []
Dir.chdir('test/unclassified')
new_dir = TestDirectory.new
new_dir.files.each do |file|
  if File.extname(file) == ".test"
    new_dir.move(file, '.', '../failed')
    testList << File.basename(file, ".test") 
  end
end
Dir.chdir("../..")
`mv results/unclassified/* results/failed/`

status = Report.test_results
status[:command] = File.basename(__FILE__)
status[:time] = Time.now
status[:tests] = testList

h = History.new
h.log(status)